name: Deploy to Server
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Step 2: Configure known_hosts for SSH
      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 138.197.38.184 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # Step 3.2: Transfer files
      - name: Transfer Files to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 138.197.38.184
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/var/www/html/radiant_hyve"
          strip_components: 1

      # Step 4: Restart or Start PM2 app
      - name: Restart or Start Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 138.197.38.184
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/radiant_hyve
             pm2 restart all
             
